terraform/distributed/README.md
terraform/per-project/README.md

Quick update to correct the GitHub urls in the documentation.

Fixing GitHub repository urls in the per-project and distributed READMEs

---

scaler/index.js
scaler/scaling-methods/base.js
scaler/test/scaling-methods/base.test.js

There was an issue with the function name being incorrect in some places, that was causing an exception in the scaler function.

Changed function name to metricValueWithinRange

---

terraform/modules/autoscaler/main.tf
terraform/modules/autoscaler/variables.tf
terraform/modules/forwarder/main.tf
terraform/modules/forwarder/variables.tf

Uniform bucket access

---

scaler/index.js
scaler/scaling-methods/base.js
scaler/scaling-methods/linear.js
scaler/scaling-methods/stepwise.js
scaler/test/sample-parameters.json
scaler/test/scaling-methods/base.test.js
scaler/test/test-utils.js
scaler/utils.js

Hi Ben
After some tests, I modified the logging from the base module to cover all the use cases and to make it clearer.
I also updated the unit tests.
PTAL
David

Granular instances - scaler implementation - part 2

---

.github/workflows/unit_tests.yaml
.gitignore
README.md
poller/README.md
poller/index.js
poller/package.json
poller/test/index.test.js
scaler/README.md
scaler/index.js
scaler/package.json
scaler/scaling-methods/base.js
scaler/scaling-methods/direct.js
scaler/scaling-methods/linear.js
scaler/scaling-methods/stepwise.js
scaler/test/index.test.js
scaler/test/sample-parameters.json
scaler/test/scaling-methods/base.test.js
scaler/test/scaling-methods/direct.test.js
scaler/test/scaling-methods/linear.test.js
scaler/test/scaling-methods/stepwise.test.js
scaler/test/test-utils.js
scaler/test/utils.test.js
scaler/utils.js
terraform/distributed/README.md
terraform/distributed/app-project/main.tf
terraform/distributed/autoscaler-project/main.tf
terraform/per-project/main.tf

Support for Spanner Granular Instances

Granular instances

---

poller/package.json
scaler/package.json
terraform/modules/spanner/main.tf

- Added num_nodes = 1 to modules/spanner/main.tf file
- Removed functions framework module for poller and scaler
- Related buganizer: http://b/205601652

Update: GSP771

---

forwarder/package.json

For issue #53 we also need to upgrade the packages for the forwarder function. This PR also aligns the PubSub library versions across the forwarder and poller.

Upgrading packages for the forwarder function.

---

terraform/modules/spanner/main.tf

This PR is a follow-on to PR #54 to address the Terraform updates to accommodate the out-of-band changes the autoscaler will be making.

Lifecycle rules for num_nodes and processing_units

---

README.md
forwarder/README.md
poller/README.md
scaler/README.md
terraform/README.md
terraform/centralized/README.md
terraform/distributed/README.md
terraform/distributed/app-project/main.tf
terraform/distributed/app-project/variables.tf
terraform/distributed/autoscaler-project/main.tf
terraform/distributed/autoscaler-project/variables.tf
terraform/modules/monitoring/.gitignore
terraform/modules/monitoring/dashboard.tpl.json
terraform/modules/monitoring/main.tf
terraform/modules/monitoring/outputs.tf
terraform/modules/monitoring/variables.tf
terraform/per-project/README.md
terraform/per-project/main.tf
terraform/per-project/variables.tf

In many cases, teams have dashboards that track important Spanner metrics.
With a starter dashboard, users can start using it right away,
so I have added the necessary modules to create a dashboard.
Refer to #8

Added Cloud Monitoring Dashboard

---

scaler/README.md
terraform/modules/monitoring/variables.tf

Even though the terraform dashboard value is set to false it still prompts for values, so I've added defaults based on the recommended thresholds.

Default values for the metrics on the default dashboard.

---

poller/index.js
poller/test/index.test.js

Added failing tests and a fix for issue #61 
This change also catches the case were both minNodes/minSize and maxNodes/maxSize are both specified in the configuration but have conflicting values.  In those cases an error is throw and the processing is stopped.

Tests and a fix for Issue 61.

---

scaler/scaler-core/scaling-methods/linear.js

This PR adds the additional structured log fields to code added in a parallel PR.

Add additional log fields

---

.eslintrc.js
.github/workflows/linters.yaml
.github/workflows/unit_tests.yaml
.mdl.rb
LICENSE
src/scaler/scaler-core/state.js
terraform/cloud-functions/distributed/README.md

This addresses missing/malformed license headers as well as additional minor formatting/text updates.

License compliance updates

---

src/package-lock.json
src/package.json
src/scaler/package-lock.json

run npm install --save on all src directories to update package-lock.json files.

Update package-lock.json files

---

.github/dependabot.yaml

Cleanup a bit and add comments, and an ignore rule for scaler-core major versions.

Add major version ignore for scaler-core

---

src/forwarder/index.js
src/poller/poller-core/index.js
src/scaler/scaler-core/index.js

This avoids potentially incorrect values in error logs emitted when handling exceptions.

Ensure variables are correctly scoped for try/catch

---

jsconfig.json
package-lock.json
package.json
src/forwarder/index.js
src/forwarder/package-lock.json
src/forwarder/package.json
src/index.js
src/poller/poller-core/index.js
src/poller/poller-core/package-lock.json
src/poller/poller-core/package.json
src/scaler/scaler-core/index.js
src/scaler/scaler-core/package-lock.json
src/scaler/scaler-core/package.json
src/scaler/scaler-core/state.js
src/scaler/scaler-core/test/index.test.js
src/scaler/scaler-core/test/scaling-methods/base.test.js
src/scaler/scaler-core/test/scaling-methods/direct.test.js
src/scaler/scaler-core/test/scaling-methods/linear.test.js
src/scaler/scaler-core/test/scaling-methods/stepwise.test.js
src/scaler/scaler-core/test/test-utils.js
src/scaler/scaler-core/utils.js

VSCode and typescript compiler can perform pre-compilation and syntax checking of JS files. 
Enable this feature, and fix all surfaced errors.
Add top level rule: `npm typecheck` which can be used (at a later date) as a pull-request pre-check.

Add Tscompiler compilation and syntax/type checking of JS files

---

.github/workflows/unit_tests.yaml

Add Node v20 to unit test matrix
Also simplifies poller and scaler tests into a single workflow job.

Add unit tests for nodejs v20

---

src/forwarder/index.js
src/forwarder/package-lock.json
src/forwarder/package.json
src/index.js
terraform/modules/forwarder/main.tf
terraform/modules/forwarder/variables.tf

- Use common logging
- Update Node version in line with other components
Fixes #175.

Update forwarder in line with poller and scaler

---

src/package-lock.json
src/package.json
src/poller/package-lock.json
src/poller/package.json
src/scaler/package.json

"run" aka runjs is a package that auto-reruns a file whenever it changes. 
It is meant to help developers re-run code during development, and is not required by autoscaler at runtime.
https://www.npmjs.com/package/run

Remove run dependancy.

---

package.json
src/package-lock.json
src/poller/package-lock.json
src/scaler/package-lock.json

add command `npm run install-all`
This command installs the required node-modules in all the src directories and updating  all the package-lock.json files by executing the command `npm install --save` in each subdirectory.

Add top level command "npm run install-all"

---

src/autoscaler-common/logger.js
src/package-lock.json
src/poller/package-lock.json
src/poller/poller-core/package-lock.json
src/poller/poller-core/package.json
src/scaler/package-lock.json
src/scaler/scaler-core/package-lock.json
src/scaler/scaler-core/package.json

This PR adds, in decreasing order of precedence:
- A check for a `LOG_LEVEL` environment variable, and if found sets the bunyan loglevel accordingly (primarily to enable detailed logging for local/developer testing)
- A check for a `NODE_ENV` environment variable, which suppresses logging if the value is `test` (primarily for readability of unit test output), and
- A default loglevel of `DEBUG`

Add LOG_LEVEL parameter, suppress logs for unit tests

---

.github/release-please.yml
.github/workflows/linters.yaml
package.json

Adds release please config for master branch
Requires conventional commit messages from now on...

chore: Configure Release please for master branch

---

package-lock.json
package.json

Fixes: Express.js Open Redirect in malformed URLs - GHSA-rv95-896h-c2vc

fix(deps): Update express to 4.19.2

---

.eslintignore
.gcloudignore
.gitignore
README.md
configeditor/README.md
configeditor/build-configeditor.sh
configeditor/index.html
configeditor/index.mjs
package.json

feat: Add JSON editor for schema-validated editing of configs

---

package.json

Xargs allow macos (-0 == --null) [ref](https://www.man7.org/linux/man-pages/man1/xargs.1.html)

fix: macos compatible xargs (-0 == --null)

---

package.json

This is to enable interactive debugging.

chore: fix debug commands

---

terraform/cloud-functions/distributed/app-project/.terraform.lock.hcl
terraform/cloud-functions/distributed/app-project/main.tf
terraform/cloud-functions/distributed/autoscaler-project/.terraform.lock.hcl
terraform/cloud-functions/distributed/autoscaler-project/main.tf
terraform/cloud-functions/per-project/.terraform.lock.hcl
terraform/cloud-functions/per-project/main.tf
terraform/gke/decoupled/.terraform.lock.hcl
terraform/gke/decoupled/main.tf
terraform/gke/unified/.terraform.lock.hcl
terraform/gke/unified/main.tf
terraform/modules/autoscaler-cluster/main.tf

* hashicorp/google -> 6.9.0
* hashicorp/kubernetes -> 2.33.0
* terraform-google-modules/kubernetes-engine/* -> 34.0.0

fix(deps): update terraform module versions

---

terraform/README.md
terraform/gke/README.md

- Add productionization tips
- Remove spaces from GKE links

docs: minor docs updates
