cloudspannerecosystem/autoscaler

- terraform/modules/scheduler/main.tf
- terraform/modules/scheduler/variables.tf
Cloud Scheduler UI does not know about the default Etc/UTC time zone
so use a known timezone instead to prevent UI errors.
> Use known time_zone for Scheduler job.

- .github/linters.yaml
Starting to work on Issue #16.
Fixed some additional markdown linter issues and adding a GitHub Action to automate linting.
> Adding a GitHub Action to run markdownlint 

- poller/README.md
- poller/index.js
- poller/package.json
- poller/test/index.test.js
This PR has the implementation for custom metrics (Issue #10).  
If the metric name is not found in the current set of metrics for a Spanner instance it:
* merges default values
* check to make sure all required fields are present and valid
* then adds a new metric to the metrics array for that Spanner instance
> Implementation for custom metrics, for Issue #10

- poller/README.md
> minor: fix typo in poller example

- .github/workflows/linters.yaml
Markdown linting broke because the tag for the markdown linter got changed to `main`.  This PR updates the actions to use the correct tag.
> Fixing the markdown linter action

- terraform/modules/autoscaler/main.tf
- terraform/modules/forwarder/main.tf
- terraform/modules/spanner/main.tf
As described in Issue #39 the modules were using iam_binding which is authoritative which will override any pre-existing roles, which is likely the case with Cloud Spanner deployments. This update changes to iam_member which is an additive which will be safer for resources which might already have iam roles.
> Issue #39 - Updating Terraform to use the safer iam_member instead of binding.

- README.md
- poller/README.md
- poller/index.js
- poller/test/index.test.js
This change adds support for processing units in the Poller function.
The config defaults the units to `NODES`.  If nodes are provided it merges in settings based around nodes and also copies those values into the new `minSize` and `maxSize`, and logs a deprecation warning. If processing units are provided as the units but the `minNodes` or `maxNodes` are used for the sizing params an error is thrown.
> Added support for processing units in the configuration processing.

- poller/README.md
- scaler/state.js
- terraform/distributed/README.md
- terraform/per-project/README.md
When Firestore is Datastore mode, currently the autoscaler is not able to use,
so I added an option tracking states in spanner.
Refer to #2
> Added option tracking states in spanner

- poller/package.json
- scaler/package.json
- terraform/distributed/app-project/main.tf
- terraform/distributed/app-project/variables.tf
- terraform/distributed/autoscaler-project/main.tf
- terraform/distributed/autoscaler-project/variables.tf
- terraform/per-project/README.md
- terraform/per-project/main.tf
- terraform/per-project/variables.tf
Fix for issue #65 : 
Removed the following variables from the root terraform modules for the distributed and per-project deployments:
* dashboard_threshold_high_priority_cpu_percentage
* dashboard_threshold_rolling_24_hr_percentage
* dashboard_threshold_storage_percentage
A user can modify the defaults directly in the monitoring module, or pass the values by modifying the root module.
> Remove dashboard variables without default from root modules

- terraform/gke/README.md
This adds to the GKE documentation with a short `Troubleshooting` section for common issues, and an additional note on the extra configuration step if using Firebase.
> Add troubleshooting guidance for common issues

- kubernetes/autoscaler-config/autoscaler-config.yaml.template
- scaler/scaler-core/state.js
- terraform/gke/README.md
- terraform/gke/main.tf
- terraform/gke/variables.tf
This PR updates the Spanner state store handling as follows:
- Updates GKE deployment option + docs to match new configuration options added in:
#81 
- Updates the template for GKE autoscaler configuration to match the above
- Updates the Spanner state store logic so that the target scaling instance is used as the state database key, fixing:
#76
> Updates to Spanner state store

- kubernetes/autoscaler-config/autoscaler-config-hourly.yaml.template
- kubernetes/autoscaler-config/autoscaler-config.yaml.template
- kubernetes/autoscaler-pkg/README.md
- kubernetes/autoscaler-pkg/poller/README.md
- kubernetes/autoscaler-pkg/poller/poller-hourly.yaml
- kubernetes/autoscaler-pkg/scaler/README.md
- poller/index.js
- terraform/gke/README.md
This PR allows for the location of the Poller configuration file to be specified via environment variable, which opens up the possibility of multiple autoscaling schedules for either the same or multiple Spanner instances. If no location is specified, a default location is used.
> Allow for config location to be specified

- terraform/modules/autoscaler-cluster/main.tf
- terraform/modules/autoscaler-cluster/variables.tf
This is because the stable channel default version is now 1.24, which is not (yet) supported by the [workload identity module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/workload-identity/README.md).
> Lock Kubernetes version to 1.23

- poller/index.js
- poller/poller-core/index.js
- poller/poller-core/utils.js
- scaler/index.js
- scaler/scaler-core/index.js
- scaler/scaler-core/scaling-methods/base.js
- scaler/scaler-core/scaling-methods/direct.js
- scaler/scaler-core/scaling-methods/linear.js
- scaler/scaler-core/scaling-methods/stepwise.js
- scaler/scaler-core/utils.js
This PR adds additional structure to each logline, using named arguments for the following fields, which are passed through to the JSON output:
`severity`
`projectId`
`instanceId`
`payload`
The `message` field is retained as unnamed for backwards compatibility.
This means that all loglines are parsed as JSON and can be queried via Cloud Logging. Fixes #86.
> Move to (more) structured logs

- terraform/cloud-functions/per-project/main.tf
- terraform/modules/scheduler/main.tf
- terraform/modules/scheduler/variables.tf
This PR adds new variables for basic settings to be passed into the Cloud Scheduler module. The new variables provide an easy way for users to specify common settings when managing a single spanner instance.
The PR also adds a variable to directly specify JSON that should be used by Cloud Scheduler.  This variable allows users to define configuration for multiple spanners and set configuration values that are directly enabled via Terraform variables.
> Add option for specifying config directly as JSON

- terraform/gke/README.md
Adds an entry to the "troubleshooting" section in the `README.md` on how to pull autoscaler logs from Cloud Logging.
> Add note on GKE log retrieval

- poller/poller-core/index.js
Multi-region Cloud Spanner deployments were over-reporting on metrics in the poller because the metric value for each location was being summed.  For example, if every location was seeing 5% the reported CPU utilization was 15%, this could even cause observed utilization to be greater than 100%.
To resolve this issue a group_by has been added to the aggregator and the maximum metric values is selected across regions. This allows a scaling event to be triggered if a read-only region crosses the threshold, keeping all regions below the utilization threshold.
> Adding group by to the aggregator for the metrics query.

- README.md
- terraform/cloud-functions/README.md
- terraform/gke/README.md
- terraform/modules/scheduler/main.tf
This PR adds an optional Terraform stanza that can be applied to allow changes made directly to the Cloud Scheduler configuration to be ignored by Terraform. This means that the source of truth is configurable and better supports idempotency. The addition of the `retry_config` stanza is to ensure that default values added by the back-end are reflected in the Terraform config to avoid permadiff. Fixes #105.
> Add optional config to support idempotency

- README.md
This change updates the support state to communicate that users may now use Cloud Spanner support channels.
> Updating support statement.

- terraform/modules/autoscaler-base/main.tf
- terraform/modules/spanner/main.tf
This PR simplifies and makes more granular the permissions for the Poller service account by introducing a custom IAM role (in the same way as is currently done for the Scaler component). This addresses two issues:
- IAM permissions for the Poller component service account were multiply assigned in different Terraform source files
- Overlapping IAM roles were being applied (`roles/spanner.viewer` and `roles/monitoring.viewer`), which made reasoning about the permissions more difficult
Fixes #111.
> Simplify and restrict Poller service account permissions

- terraform/cloud-functions/distributed/app-project/.terraform.lock.hcl
- terraform/cloud-functions/per-project/.terraform.lock.hcl
- terraform/modules/spanner/main.tf
This PR adds a random (hex) string suffix to the identifiers of the two created custom roles, making them of the form:
- `spannerAutoscalerMetricsViewer_hhhhhh`
- `spannerAutoscalerCapacityManager_hhhhhh`
This means that (re)build operations will succeed without encountering the errors described in #115, which this PR fixes.
> Add random suffix to custom role IDs

- scaler/README.md
It's not super helpful to mention that `LINEAR` scaling uses cross-multiplication to calculate a new instance size that is proportional to metrics in some way, and then not actually describe the calculation.  In fact, it's a little hostile to instead provide a pedantic link to the wikipedia page on Cross-multiplication.
In this PR we link to the line in code that performs the calculation and also explain just what is meant by this line.
> Updated scaler readme to be less pedantic

- .github/workflows/unit_tests.yaml
- .gitignore
- poller/Dockerfile
- poller/package-lock.json
- poller/poller-core/index.js
- poller/poller-core/package-lock.json
- poller/poller-core/package.json
- scaler/Dockerfile
- scaler/package-lock.json
- scaler/scaler-core/package-lock.json
- scaler/scaler-core/package.json
- terraform/modules/autoscaler-functions/main.tf
- terraform/modules/autoscaler-functions/variables.tf
This PR brings the version of NodeJS up to the recommended version 18 for GKE (minor image change, to be updated to a `nonroot` image in a future PR) and Cloud Functions (from EOS version 10). As well as this there are some related dependency version updates, and the addition of the `package-lock.json` files to ensure that dependency versions are consistent. This change was initiated based on findings from #122.
> NodeJS and dependency version updates

- .github/workflows/unit_tests.yaml
- poller/README.md
- poller/poller-core/index.js
The current behavior hard code the scaler url to `http://scaler`.
This PR add support for custom scaler URL while keeping the same behavior by default.
Upgrade tests from nodejs 10 to 18 since `||=` is not supported by the current version.
This is an actively supported version and used in the Dockerfile of the repository
> Update poller: add support for scalerURL

- poller/poller-core/index.js
- scaler/scaler-core/index.js
- terraform/modules/autoscaler-cluster/main.tf
- terraform/modules/autoscaler-functions/main.tf
This PR adds a `user-agent` string to the `poller`, `scaler`, and to the Terraform definitions for the two main deployment models (Cloud Functions and GKE).
> Add user-agent string

- poller/poller-core/index.js
This PR introduces a fix to the `poller` component related to the recent [updates to package versions](https://github.com/cloudspannerecosystem/autoscaler/pull/124):
- Adds missing `async`/`await` to ensure that promises are not left unresolved
- Removes increased timeout for gax `setPublishOptions` (which likely was masking the above issue)
> Fix for new package behaviour

- poller/README.md
Recently, in our product, when stepSize was set to `1N` in reference to the Default Value in the documentation, the `suggestedSize` was undefined and scaler did not work.
We believe that this problem is caused by the misleading default value in the documentation, so we have added a note in the description not to include the unit.
> Add instruction to not include unit (`N` or `PU`) in the `stepSize` value to prevent configuration errors.

- .github/dependabot.yaml
Add missing `ignore` to Dependabot configuration.
> Add missing 'ignore' to Dependabot configuration.

- terraform/cloud-functions/distributed/app-project/main.tf
- terraform/cloud-functions/distributed/app-project/variables.tf
- terraform/cloud-functions/distributed/autoscaler-project/main.tf
- terraform/cloud-functions/distributed/autoscaler-project/variables.tf
- terraform/cloud-functions/per-project/main.tf
- terraform/cloud-functions/per-project/test/per_project_e2e_test.go
- terraform/cloud-functions/per-project/variables.tf
- terraform/gke/decoupled/main.tf
- terraform/gke/decoupled/variables.tf
- terraform/gke/unified/main.tf
- terraform/gke/unified/variables.tf
- terraform/modules/autoscaler-base/variables.tf
- terraform/modules/autoscaler-functions/variables.tf
- terraform/modules/firestore/variables.tf
- terraform/modules/forwarder/variables.tf
- terraform/modules/scheduler/main.tf
- terraform/modules/scheduler/variables.tf
- terraform/modules/spanner/variables.tf
Following the discovery of missing location (region/zone) parameters that were causing issues during deployment, this PR removes all default region and zone parameters in favour of requiring explicit configuration. Removing these defaults does not require a change to documentation and means that any misconfiguration (or as-yet-undiscovered Terraform issues) will be easier to debug.
> Require explicit region/zone parameters, remove defaults

- terraform/cloud-functions/distributed/README.md
- terraform/cloud-functions/per-project/README.md
- terraform/gke/README.md
- Explicitly enable additional services
- State more clearly the precise Spanner instance name to use
> Minor docs updates

- terraform/cloud-functions/distributed/README.md
- terraform/cloud-functions/distributed/app-project/main.tf
- terraform/cloud-functions/distributed/app-project/variables.tf
- terraform/cloud-functions/distributed/autoscaler-project/main.tf
- terraform/cloud-functions/distributed/autoscaler-project/variables.tf
- terraform/cloud-functions/per-project/README.md
- terraform/cloud-functions/per-project/main.tf
- terraform/cloud-functions/per-project/variables.tf
- terraform/gke/decoupled/main.tf
- terraform/gke/decoupled/variables.tf
- terraform/gke/unified/main.tf
- terraform/gke/unified/variables.tf
The `zone` parameter is no longer directly used and only supplied as a parameter to the provider for a default value.
> Remove 'zone' parameter

- src/package-lock.json
- src/scaler/package-lock.json
- src/scaler/scaler-core/package-lock.json
Updates `es5-ext` package to address https://github.com/advisories/GHSA-4gmj-3p3h-gm8h which was causing code health checks to fail.
> Bump es5-ext package due to DoS vulnerability

- src/package-lock.json
- src/poller/package-lock.json
- src/scaler/package-lock.json
- terraform/modules/autoscaler-functions/main.tf
This PR explicitly excludes all `node_modules` directories managed as part of the `src` tree from being archived and uploaded as the Cloud Functions source -- explicitly in the absence of a `glob` capability in the Terraform `archive_file` data source. This means that local dependency management becomes easier -- as part of this PR are some additional dependency updates -- and the package uploaded to GCS becomes significantly smaller.
> Exclude node_modules from CF archive creation

- src/scaler/scaler-core/state.js
- src/scaler/scaler-core/test/state.test.js
Fixes #213 
Migrations location of state doc in Firestore storage from 
```
autoscaler/${instanceId}
```
to
```
spannerAutoscaler/state/projects/${projectId}/instances/${instanceId}
```
Avoids clashes when instances have the same names in different projects
> Migrate to using new docPath for Firestore including projectID 

- .github/workflows/unit_tests.yaml
- .npmrc
- package-lock.json
- package.json
- src/.npmrc
- src/package-lock.json
- src/package.json
BREAKING CHANGE: Node v16 has been end-of-life since 2023-09-11, so testing is removed for this version of Node.
Added node version enforcement to package.json.
> feat!: Remove support for node v16

- README.md
- src/autoscaler-common/package-lock.json
- src/forwarder/package-lock.json
- src/package-lock.json
- src/poller/README.md
- src/poller/package-lock.json
- src/poller/poller-core/package-lock.json
- src/scaler/package-lock.json
- src/scaler/scaler-core/index.js
- src/scaler/scaler-core/package-lock.json
- src/scaler/scaler-core/package.json
- src/scaler/scaler-core/state.js
- src/scaler/scaler-core/test/index.test.js
- src/scaler/scaler-core/test/state.test.js
- src/scaler/scaler-core/test/test-utils.js
- src/scaler/scaler-core/test/utils.test.js
- terraform/cloud-functions/distributed/README.md
- terraform/cloud-functions/per-project/README.md
- terraform/gke/README.md
- terraform/modules/spanner/main.tf
BREAKING CHANGE: Spanner State Store requires DB schema update.
Store the Scaling Operation ID in the State object and check it next time scaler runs.
This allows scaler to pull operation failure messages from the LRO, and also to use the LRO completion time as the last successful scaling time for cooldown.
Update readme and terraform with new Spanner schema defs
Required schema update:
```sql
ALTER TABLE spannerAutoscaler ADD COLUMN IF NOT EXISTS lastScalingCompleteTimestamp TIMESTAMP;
ALTER TABLE spannerAutoscaler ADD COLUMN IF NOT EXISTS scalingOperationId STRING(MAX);
```
Example log messages when performing LRO checks: 
Success
> ----- PROJECT_ID/INSTANCE_ID: Last scaling request for {"processingUnits":2000} SUCCEEDED. Started: 2024-03-08T17:19:59.471332Z, completed: …
> feat!: Add monitoring of Scaling Long Running Operations

- .commitlintrc.json
- .husky/commit-msg
- .husky/pre-commit
- package-lock.json
- package.json
Husky is a package that enforces pre-commit checks for all cloned repos. 
Add checks which run: 
npm run eslint
npm run mdlint
npm run typecheck
npm test
and verify the commit message is in a format matching the conventional-commit app.
> chore(precommit): Add husky precommit checks to run linters and tests.

- src/autoscaler-common/counters_base.js
- src/autoscaler-common/logger.js
- src/forwarder/index.js
- src/index.js
- src/poller/index.js
- src/poller/poller-core/index.js
- src/scaler/index.js
- src/scaler/scaler-core/index.js
- src/scaler/scaler-core/state.js
- src/scaler/scaler-core/utils.js
Adds bunyan Error serializer (to log {err:err} correctly with stack trace etc. Fix log messages to include error message in log message
Before: exception stack traces were not included in logging: 
```js
err=new Error('myerror');
logger.error({err:err, message:`Failed`});
{
"timestamp": {
"seconds": 1712143463,
"nanos": 476000070
},
"severity": "ERROR",
"logging.googleapis.com/insertId": "..........5RSfIdnw_0SuufwA49eSIJ",
"name": "redis-cluster-autoscaler",
"hostname": "dastardly.c.googlers.com",
"pid": 208009,
"level": 50,
"err": {},
"message": "Failed",
"msg": "myerror",
"time": "2024-04-03T11:24:23.476Z",
"v": 0,
"logName": "projects/redis-autoscaler/logs/redis-cluster-autoscaler"
}
```
After, includes err object correctly with stack trace
```js
err=new Error('myerror'); …
```
> fix: Correctly log Exceptions

- src/autoscaler-common/types.js
- src/poller/poller-core/index.js
- src/scaler/README.md
- src/scaler/scaler-core/scaling-methods/base.js
- src/scaler/scaler-core/test/scaling-methods/base.test.js
- src/scaler/scaler-core/test/state.test.js
Instances configured with <1000 PUs only support 10 DBs per 100 PUs so clamp the minimum size to the relevant number of PUs
Fixes #286
> feat: Take into account number of databases in an instance

- src/autoscaler-common/counters_base.js
- src/poller/README.md
- src/scaler/scaler-core/counters.js
- src/scaler/scaler-core/index.js
- src/scaler/scaler-core/state.js
- src/scaler/scaler-core/test/index.test.js
- src/scaler/scaler-core/test/state.test.js
- src/scaler/scaler-core/test/test-utils.js
- terraform/cloud-functions/distributed/README.md
- terraform/cloud-functions/per-project/README.md
- terraform/gke/README.md
- terraform/modules/spanner/main.tf
Adds a distribution metric for scaling duration, and only records success once operation is complete
Requires an update to the spanner schema to correctly apply metric parametes.
> feat: Add metric for scaling duration

- package-lock.json
- package.json
- src/autoscaler-common/counters_base.js
fix(deps): update dependency @google-cloud/opentelemetry-cloud-monitoring-exporter to ^0.18.0
Remove FAAS_ID workaround for metrics, as that is no longer needed.
> fix: Update OTEL GCM exporter and remove FAAS workaround

- markdown-link-checker.json
- package.json
- terraform/gke/README.md
ignore CHANGELOG.md file and links to console.cloud.google.com
> chore: improve markdown-link-checker speed

- package-lock.json
- package.json
- terraform/cloud-functions/distributed/app-project/.terraform.lock.hcl
- terraform/cloud-functions/distributed/app-project/main.tf
- terraform/cloud-functions/distributed/autoscaler-project/.terraform.lock.hcl
- terraform/cloud-functions/distributed/autoscaler-project/main.tf
- terraform/cloud-functions/per-project/.terraform.lock.hcl
- terraform/cloud-functions/per-project/main.tf
- terraform/gke/decoupled/.terraform.lock.hcl
- terraform/gke/decoupled/main.tf
- terraform/gke/unified/.terraform.lock.hcl
- terraform/gke/unified/main.tf
- terraform/modules/autoscaler-cluster/main.tf
chore(deps): update dependency mocha to ^10.6.0
chore(deps): update terraform terraform-google-modules/kubernetes-engine/google to ~> 31.1.0
chore(deps): update dependency typescript to ^5.5.3
chore(deps): update terraform google to ~> 5.36.0
replaces #337, #336, #335, #334
> chore(deps): Bulk update of Renovate bumps

- src/autoscaler-common/counters_base.js
This is to remove a persistent `WARNING` level logline in the Cloud Logging output for GKE deployment.
> fix: Populate OpenTelemetry compression parameter

- src/scaler/scaler-core/index.js
- src/scaler/scaler-core/test/index.test.js
This is to ensure that logging output matches the underlying behaviour in the case of a defaulted scaling method.
> fix: Retain defaulted scaling method name

- src/autoscaler-common/counters_base.js
- terraform/modules/monitoring/dashboard.json.tftpl
This additionally updates the metrics domain used by the Cloud Functions deployment from `custom.googleapis.com` to `workload.googleapis.com` (to match the GCP Metrics exporter for the OpenTelemetry collector).
> feat!: Add scaling duration dashboard

- package-lock.json
- package.json
Sinon v15 has a dependancy on a vulnerable version of path-to-regexp Fixed in sinon v17
> fix(deps): update sinon and nyc to resolve npm audit

- .github/workflows/codehealth.yaml
- .husky/pre-commit
- package.json
- terraform/cloud-functions/distributed/app-project/.terraform.lock.hcl
- terraform/cloud-functions/distributed/app-project/main.tf
- terraform/cloud-functions/distributed/autoscaler-project/.terraform.lock.hcl
- terraform/cloud-functions/distributed/autoscaler-project/main.tf
- terraform/cloud-functions/per-project/.terraform.lock.hcl
- terraform/cloud-functions/per-project/main.tf
- terraform/gke/decoupled/.terraform.lock.hcl
- terraform/gke/decoupled/main.tf
- terraform/gke/unified/.terraform.lock.hcl
- terraform/gke/unified/main.tf
- terraform/modules/autoscaler-base/main.tf
- terraform/modules/autoscaler-base/outputs.tf
- terraform/modules/autoscaler-cluster/main.tf
- terraform/modules/autoscaler-functions/main.tf
- terraform/modules/autoscaler-functions/variables.tf
- terraform/modules/forwarder/main.tf
New projects by default do not give the default compute service account the required roles to run a cloud build. Therefore the cloud functions do not deploy.
Update the TF scripts to create a build-sa service account and use that when deploying the Cloud Functions.
Also update versions of Terraform modules to the latest
> fix: use a custom service account for Cloud Build

- terraform/modules/autoscaler-base/main.tf
- terraform/modules/autoscaler-cluster/main.tf
- terraform/modules/autoscaler-functions/main.tf
- terraform/modules/forwarder/main.tf
- terraform/modules/scheduler/main.tf
* This includes terraform format changes
> Fix: terraform always specify project

- kubernetes/decoupled/autoscaler-pkg/otel-collector/otel-collector.yaml
- kubernetes/unified/autoscaler-pkg/otel-collector/otel-collector.yaml
This is mostly for completeness, as the resource utilization is minimal for this level of telemetry.
> fix: add resource requests/limits to otel collector

- terraform/modules/autoscaler-cluster/main.tf
fixes terraform validate issues in v3.0.0
> fix(tf): lock versions of terraform-google-modules/kubernetes-engine

- terraform/modules/autoscaler-base/main.tf
This is to enable checks for cached images from previous builds.
> fix(tf): allow build SA to read AR

- terraform/modules/autoscaler-functions/main.tf
- terraform/modules/autoscaler-functions/variables.tf
By default the container gets assigned 167m CPU. 
For us: moving to the min (0.08) results in ~50% cost savings and small increase in runtime.
Partially address https://github.com/cloudspannerecosystem/autoscaler/issues/440
<details>
<summary>BEFORE</summary>
Mean runtime 7.8s
Container CPU
</details>
<details>
<summary>AFTER</summary>
Mean runtime 9.1s
</details>
> feat: parameterize Cloud Run functions available CPU

- terraform/modules/autoscaler-functions/main.tf
- terraform/modules/autoscaler-functions/variables.tf
breaking change
The previous terraform configuration allowed users to update the max_instance_count of each function in the console and have terraform ignore the change. This change puts max_instance_count under terraform control and is therefore a breaking change for users who were relying on terraform never updating the value they set. It does not seem possible to ignore_changes selectively (EG if the max_instance_count var was null).
The default of null (which then defaults to 100 in Cloud Run) remains unchanged.
Partially address https://github.com/cloudspannerecosystem/autoscaler/issues/440
<details>
<summary>BEFORE</summary>
</details>
<details>
<summary>AFTER</summary>
</details>
> feat!: parameterize Cloud Run functions instance count 

- terraform/gke/README.md
Fixed typo at `terraform/gke/README.md`
> fix(docs): fixed typo at gke unified model
